# Generated by Django 6.0.3 on 2026-03-09 19:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_eventos_usuario'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='eventos',
            table='eventos',
        ),
    ]
